insert into genres (name) values
('Ficção Científica'),
('Fantasia'),
('Distopia'),
('Terror/Horror'),
('Suspense e Mistério'),
('Romance'),
('Ficção Histórica'),
('Aventura'),
('Drama'),
('Contos e Crônicas'),
('Poesia'),
('HQ e Manga'),
('Biografia e Autobiografia'),
('História'),
('Filosofia'),
('Psicologia'),
('Autoajuda'),
('Negócios e Finanças'),
('Tecnologia e Computação'),
('Ciências Exatas'),
('Religião e Espiritualidade'),
('Arte e Design'),
('Dicionário'),
('Outros');